// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using albiondata_sql_dotNet;

#nullable disable

namespace albiondata_sql_dotNet.Migrations
{
    [DbContext(typeof(ConfiguredContext))]
    partial class ConfiguredContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlbionData.Models.GoldPrice", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<long>("Price")
                        .HasColumnType("bigint")
                        .HasColumnName("price");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("gold_prices", (string)null);
                });

            modelBuilder.Entity("AlbionData.Models.MarketHistoryDB", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<int>("AggregationType")
                        .HasColumnType("int")
                        .HasColumnName("aggregation");

                    b.Property<decimal>("ItemAmount")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("item_amount");

                    b.Property<string>("ItemTypeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("item_id");

                    b.Property<int>("Location")
                        .HasColumnType("int")
                        .HasColumnName("location");

                    b.Property<byte>("QualityLevel")
                        .HasColumnType("tinyint")
                        .HasColumnName("quality");

                    b.Property<decimal>("SilverAmount")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("silver_amount");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasAlternateKey("ItemTypeId", "QualityLevel", "Location", "Timestamp", "AggregationType")
                        .HasName("Main");

                    b.ToTable("market_history", (string)null);
                });

            modelBuilder.Entity("AlbionData.Models.MarketOrderDB", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<decimal>("AlbionId")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("albion_id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<string>("AuctionType")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("auction_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<byte>("EnchantmentLevel")
                        .HasColumnType("tinyint")
                        .HasColumnName("enchantment_level");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires");

                    b.Property<long>("InitialAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("initial_amount");

                    b.Property<string>("ItemTypeId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("item_id");

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("location");

                    b.Property<byte>("QualityLevel")
                        .HasColumnType("tinyint")
                        .HasColumnName("quality_level");

                    b.Property<decimal>("UnitPriceSilver")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasAlternateKey("AlbionId")
                        .HasName("AlbionId");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("Deleted");

                    b.HasIndex("DeletedAt", "Expires", "UpdatedAt")
                        .HasDatabaseName("Expired");

                    b.HasIndex("ItemTypeId", "UpdatedAt", "DeletedAt")
                        .HasDatabaseName("TypeId");

                    b.HasIndex("ItemTypeId", "AuctionType", "LocationId", "UpdatedAt", "DeletedAt")
                        .HasDatabaseName("Main");

                    b.ToTable("market_orders", (string)null);
                });

            modelBuilder.Entity("AlbionData.Models.MarketStat", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("item_id");

                    b.Property<int>("Location")
                        .HasColumnType("int")
                        .HasColumnName("location");

                    b.Property<decimal>("PriceAverage")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price_avg");

                    b.Property<decimal>("PriceMax")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("price_max");

                    b.Property<decimal>("PriceMin")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("price_min");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasAlternateKey("ItemId", "Location", "Timestamp");

                    b.ToTable("market_stats", (string)null);
                });

            modelBuilder.Entity("albiondata_sql_dotNet.MarketOrderExpiredDB", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<decimal>("AlbionId")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("albion_id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<string>("AuctionType")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("auction_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<byte>("EnchantmentLevel")
                        .HasColumnType("tinyint")
                        .HasColumnName("enchantment_level");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires");

                    b.Property<long>("InitialAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("initial_amount");

                    b.Property<string>("ItemTypeId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("item_id");

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("location");

                    b.Property<byte>("QualityLevel")
                        .HasColumnType("tinyint")
                        .HasColumnName("quality_level");

                    b.Property<decimal>("UnitPriceSilver")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasAlternateKey("AlbionId")
                        .HasName("AlbionId1");

                    b.ToTable("market_orders_expired", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
